### ISSUE TITLE
"Unable to complete U2F registration" with self-hosted instance

### ISSUE THREAD

**Issue by m4tx** [bitwarden/web#462]
I have the latest (1.32) version of Bitwarden self-hosted. When I try to add a Fido U2F key to my account, after clicking "Read Key" (which apparently works fine - a message _Click the "Save" button below to enable this security key for two-step login._ is displayed) and clicking Save, a popup appears with an error message:
```
An error has occurred.
Unable to complete U2F registration.
```
the call to `/api/two-factor/u2f` that the browser makes returns HTTP 400. I can see the following exception in my logs (`logs/api/Api`):
```
2020-02-18 11:19:16.503 +00:00 [Error] Complete U2F registration error.
U2F.Core.Exceptions.U2fException: Exception of type 'U2F.Core.Exceptions.U2fException' was thrown.
   at U2F.Core.Crypto.CryptoService.CheckSignature(ICipherParameters certificate, Byte[] signedbytes, Byte[] signature)
   at U2F.Core.Models.RawRegisterResponse.CheckSignature(String appId, String clientData)
   at U2F.Core.Crypto.U2F.FinishRegistration(StartedRegistration startedRegistration, RegisterResponse tokenResponse, HashSet`1 facets)
   at Bit.Core.Services.UserService.CompleteU2fRegistrationAsync(User user, Int32 id, String name, String deviceResponse) in /home/appveyor/projects/server/src/Core/Services/Implementations/UserService.cs:line 353
```
If that makes any difference, I have recently updated my `config.yml` and `env/global.override.env`, because it didn't include `https` at the beginning of my URLs, but I have executed `bitwarden.sh rebuild` afterwards. I am using the standard `bitwarden.sh` script inside an LXD container and a separate nginx reverse proxy. I am also able to successfully add the same YubiKey on my `bitwarden.com` account. I have confirmed the problem both on Firefox and Chromium (on Linux).

**Comment by kspearrin** [comment]
What does your app-id.json file show for the URL? Does it have https? https://yourdomain.com/app-id.json

**Comment by m4tx** [comment]
This is my `app-id.json`:
```
{
  "trustedFacets": [
    {
      "version": {
        "major": 1,
        "minor": 0
      },
      "ids": [
        "https://bitwarden.xxx.yyy.com",
        "ios:bundle-id:com.8bit.bitwarden",
        "android:apk-key-hash:dUGFzUzf3lmHSLBDBIv+WaFyZMI"
      ]
    }
  ]
}
```
`xxx.yyy` is of course the actual (and reachable) domain name.

**Comment by kspearrin** [comment]
That looks correct. It seems like the container doesn't have access to some underlying crypto library or something.

**Comment by m4tx** [comment]
I have moved the Bitwarden instance outside the LXD container (to the host machine) and enrolling Fido U2F key still throws the exact same error.

How this be further debugged?

**Comment by adam-olson** [comment]
This issue is also happening to me as well, running on a Synology 713+. Had support take a look at it last year and they also figured it was something going on with the crypto primitives of the OS when trying to sign the registration request. Would be great to find a fix for this issue.

**Comment by david-freistrom** [comment]
Any news here?
We have the same issue on Kubernetes.
app-id looks correct with https but we get the same error.

**Comment by silvar05123** [comment]
I have the same error ....

**Comment by raccettura** [comment]
I think I'm  having the same problem as well with a dockerized installation.

```
2021-05-05 02:25:16.899 +00:00 [Error] Complete U2F registration error.
U2F.Core.Exceptions.U2fException: Exception of type 'U2F.Core.Exceptions.U2fException' was thrown.
   at U2F.Core.Crypto.CryptoService.CheckSignature(ICipherParameters certificate, Byte[] signedbytes, Byte[] signature)
   at U2F.Core.Crypto.CryptoService.CheckSignature(X509Certificate attestationCertificate, Byte[] signedBytes, Byte[] signature)
   at U2F.Core.Models.RawRegisterResponse.CheckSignature(String appId, String clientData)
   at U2F.Core.Crypto.U2F.FinishRegistration(StartedRegistration startedRegistration, RegisterResponse tokenResponse, HashSet`1 facets)
   at Bit.Core.Services.UserService.CompleteU2fRegistrationAsync(User user, Int32 id, String name, String deviceResponse) in /home/runner/work/server/server/src/Core/Services/Implementations/UserService.cs:line 405
```

**Comment by adam-olson** [comment]
Updated to the new version that just came out and now I am able to setup my keys using the WebAuthn implementation with no errors.

**Comment by Hinton** [comment]
Closing this since it's most likely resolved with the WebAutn migration. Feel free to re-open if it persists.
